# Generated by Django 4.1 on 2022-08-19 13:28

import base.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozition', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('exactly_about_us', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=70)),
                ('text', models.TextField(max_length=500)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-done',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(max_length=2000, unique=True)),
                ('event_price', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to=base.models.Event.get_date_name)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'События',
                'verbose_name_plural': 'События',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozition', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to=base.models.Galery.get_date_name)),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('mail', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid mail', regex='^[^-|_]\\w*[-{0,1}]?\\w*?[@]?\\w*(.com)?$')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone', regex='^[+]?\\d{8,14}$')])),
                ('date', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid date', regex='^(\\d{1,2})([-: .]\\d{1,2})?(-\\d{4})?$')])),
                ('time', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid time', regex='^(\\d{1,2})([-: ]\\d{1,2})?$')])),
                ('number_of_people', models.SmallIntegerField(validators=[django.core.validators.RegexValidator(message='Invalid time', regex='^[1-5][1-9]?$')])),
                ('text', models.TextField(blank=True, max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('timeadd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-timeadd', '-is_processed'),
            },
        ),
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('about', models.TextField(max_length=2000)),
                ('picture', models.ImageField(upload_to=base.models.Specials.get_date_name)),
                ('pozition', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Cпециальные предложения',
                'verbose_name_plural': 'Cпециальные предложения',
            },
        ),
        migrations.CreateModel(
            name='VideoAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('preview', models.ImageField(upload_to=base.models.VideoAboutUs.get_date_name)),
                ('video_link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Обзорное видео',
                'verbose_name_plural': 'Обзорное видео',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('ingredient', models.CharField(max_length=300)),
                ('position', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to=base.models.Dish.get_date_name)),
                ('in_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
            options={
                'verbose_name': 'Блюда',
                'verbose_name_plural': 'Блюда',
                'ordering': ('position',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
